version: '2'
services:
  application:
    image: busybox
    volumes:
     - .:/var/www
    tty: true


  nginx:
    build: ./.docker/nginx
    expose:
      - "80"
    links:
      - php
    volumes_from:
      - application
    volumes:
      - ./var/log:/var/log/nginx
    environment:
      DNSDOCK_ALIAS: www.project.docker


  php:
    build: ./.docker/php-fpm
    expose:
      - "9000"
    volumes_from:
      - application
    volumes:
     - ./var/log:/var/log
    links:
      - mysql
      - memcached
      - redis
      - beanstalk
      - rabbitmq


  mysql:
    image: mysql
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api
      MYSQL_USER: apiuser
      MYSQL_PASSWORD: apipw


  beanstalk:
    build: ./.docker/beanstalk
    expose:
      - "11300"


  rabbitmq:
    image: rabbitmq
    expose:
      - "4369"
      - "5671"
      - "5672"
      - "25672"


  redis:
    image: redis
    expose:
      - "6379"


  memcached:
    image: memcached
    expose:
      - "11211"



